'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstValueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SecondValueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ThirdValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FirstValue() As String
            Get
                Return Me.FirstValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstValueField, value) <> true) Then
                    Me.FirstValueField = value
                    Me.RaisePropertyChanged("FirstValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SecondValue() As String
            Get
                Return Me.SecondValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SecondValueField, value) <> true) Then
                    Me.SecondValueField = value
                    Me.RaisePropertyChanged("SecondValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ThirdValue() As String
            Get
                Return Me.ThirdValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ThirdValueField, value) <> true) Then
                    Me.ThirdValueField = value
                    Me.RaisePropertyChanged("ThirdValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType2", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType2
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InfrangeriField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RankField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ScorField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsernameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VictoriiField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Infrangeri() As Integer
            Get
                Return Me.InfrangeriField
            End Get
            Set
                If (Me.InfrangeriField.Equals(value) <> true) Then
                    Me.InfrangeriField = value
                    Me.RaisePropertyChanged("Infrangeri")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Rank() As Integer
            Get
                Return Me.RankField
            End Get
            Set
                If (Me.RankField.Equals(value) <> true) Then
                    Me.RankField = value
                    Me.RaisePropertyChanged("Rank")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Scor() As Integer
            Get
                Return Me.ScorField
            End Get
            Set
                If (Me.ScorField.Equals(value) <> true) Then
                    Me.ScorField = value
                    Me.RaisePropertyChanged("Scor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Victorii() As Integer
            Get
                Return Me.VictoriiField
            End Get
            Set
                If (Me.VictoriiField.Equals(value) <> true) Then
                    Me.VictoriiField = value
                    Me.RaisePropertyChanged("Victorii")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType3", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType3
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdversarField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RezultatField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Adversar() As String
            Get
                Return Me.AdversarField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdversarField, value) <> true) Then
                    Me.AdversarField = value
                    Me.RaisePropertyChanged("Adversar")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Rezultat() As String
            Get
                Return Me.RezultatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RezultatField, value) <> true) Then
                    Me.RezultatField = value
                    Me.RaisePropertyChanged("Rezultat")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType4", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType4
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ma1Field As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ma2Field As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ma3Field As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private md1Field As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private md2Field As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private md3Field As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ma1() As Double
            Get
                Return Me.ma1Field
            End Get
            Set
                If (Me.ma1Field.Equals(value) <> true) Then
                    Me.ma1Field = value
                    Me.RaisePropertyChanged("ma1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ma2() As Double
            Get
                Return Me.ma2Field
            End Get
            Set
                If (Me.ma2Field.Equals(value) <> true) Then
                    Me.ma2Field = value
                    Me.RaisePropertyChanged("ma2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ma3() As Double
            Get
                Return Me.ma3Field
            End Get
            Set
                If (Me.ma3Field.Equals(value) <> true) Then
                    Me.ma3Field = value
                    Me.RaisePropertyChanged("ma3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property md1() As Double
            Get
                Return Me.md1Field
            End Get
            Set
                If (Me.md1Field.Equals(value) <> true) Then
                    Me.md1Field = value
                    Me.RaisePropertyChanged("md1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property md2() As Double
            Get
                Return Me.md2Field
            End Get
            Set
                If (Me.md2Field.Equals(value) <> true) Then
                    Me.md2Field = value
                    Me.RaisePropertyChanged("md2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property md3() As Double
            Get
                Return Me.md3Field
            End Get
            Set
                If (Me.md3Field.Equals(value) <> true) Then
                    Me.md3Field = value
                    Me.RaisePropertyChanged("md3")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType5", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType5
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private dmgField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private textField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property dmg() As Integer
            Get
                Return Me.dmgField
            End Get
            Set
                If (Me.dmgField.Equals(value) <> true) Then
                    Me.dmgField = value
                    Me.RaisePropertyChanged("dmg")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property text() As String
            Get
                Return Me.textField
            End Get
            Set
                If (Object.ReferenceEquals(Me.textField, value) <> true) Then
                    Me.textField = value
                    Me.RaisePropertyChanged("text")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/CheckLogin", ReplyAction:="http://tempuri.org/IService1/CheckLoginResponse")>  _
        Function CheckLogin(ByVal request As ServiceReference1.CheckLoginRequest) As ServiceReference1.CheckLoginResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Top10", ReplyAction:="http://tempuri.org/IService1/Top10Response")>  _
        Function Top10(ByVal request As ServiceReference1.Top10Request) As ServiceReference1.Top10Response
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Rank", ReplyAction:="http://tempuri.org/IService1/RankResponse")>  _
        Function Rank(ByVal request As ServiceReference1.RankRequest) As ServiceReference1.RankResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Scor", ReplyAction:="http://tempuri.org/IService1/ScorResponse")>  _
        Function Scor(ByVal request As ServiceReference1.ScorRequest) As ServiceReference1.ScorResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/UserNou", ReplyAction:="http://tempuri.org/IService1/UserNouResponse")>  _
        Function UserNou(ByVal request As ServiceReference1.UserNouRequest) As ServiceReference1.UserNouResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Clasament", ReplyAction:="http://tempuri.org/IService1/ClasamentResponse")>  _
        Function Clasament(ByVal request As ServiceReference1.ClasamentRequest) As ServiceReference1.ClasamentResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Clasamentusr", ReplyAction:="http://tempuri.org/IService1/ClasamentusrResponse")>  _
        Function Clasamentusr(ByVal request As ServiceReference1.ClasamentusrRequest) As ServiceReference1.ClasamentusrResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/UserHistory", ReplyAction:="http://tempuri.org/IService1/UserHistoryResponse")>  _
        Function UserHistory(ByVal request As ServiceReference1.UserHistoryRequest) As ServiceReference1.UserHistoryResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/EndGame", ReplyAction:="http://tempuri.org/IService1/EndGameResponse")>  _
        Function EndGame(ByVal request As ServiceReference1.EndGameRequest) As ServiceReference1.EndGameResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ChampData", ReplyAction:="http://tempuri.org/IService1/ChampDataResponse")>  _
        Function ChampData(ByVal request As ServiceReference1.ChampDataRequest) As ServiceReference1.ChampDataResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ChampName", ReplyAction:="http://tempuri.org/IService1/ChampNameResponse")>  _
        Function ChampName(ByVal request As ServiceReference1.ChampNameRequest) As ServiceReference1.ChampNameResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/BotFight", ReplyAction:="http://tempuri.org/IService1/BotFightResponse")>  _
        Function BotFight(ByVal request As ServiceReference1.BotFightRequest) As ServiceReference1.BotFightResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CheckLogin", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class CheckLoginRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public a As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public v As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal a As String, ByVal v As String)
            MyBase.New
            Me.a = a
            Me.v = v
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CheckLoginResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class CheckLoginResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public CheckLoginResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CheckLoginResult As Integer)
            MyBase.New
            Me.CheckLoginResult = CheckLoginResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Top10", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Top10Request
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Top10Response", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Top10Response
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Top10Result() As ServiceReference1.CompositeType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Top10Result() As ServiceReference1.CompositeType)
            MyBase.New
            Me.Top10Result = Top10Result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Rank", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class RankRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public user As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal user As String)
            MyBase.New
            Me.user = user
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RankResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class RankResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public RankResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RankResult As Integer)
            MyBase.New
            Me.RankResult = RankResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Scor", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ScorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public user As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal user As String)
            MyBase.New
            Me.user = user
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ScorResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ScorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public ScorResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ScorResult As Integer)
            MyBase.New
            Me.ScorResult = ScorResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="UserNou", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class UserNouRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public user As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public pass As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public email As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal user As String, ByVal pass As String, ByVal email As String)
            MyBase.New
            Me.user = user
            Me.pass = pass
            Me.email = email
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="UserNouResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class UserNouResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public UserNouResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserNouResult As Integer)
            MyBase.New
            Me.UserNouResult = UserNouResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Clasament", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ClasamentRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ClasamentResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ClasamentResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public ClasamentResult() As ServiceReference1.CompositeType2
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClasamentResult() As ServiceReference1.CompositeType2)
            MyBase.New
            Me.ClasamentResult = ClasamentResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Clasamentusr", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ClasamentusrRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public user As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal user As String)
            MyBase.New
            Me.user = user
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ClasamentusrResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ClasamentusrResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public ClasamentusrResult As ServiceReference1.CompositeType2
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClasamentusrResult As ServiceReference1.CompositeType2)
            MyBase.New
            Me.ClasamentusrResult = ClasamentusrResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="UserHistory", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class UserHistoryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public user As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal user As String)
            MyBase.New
            Me.user = user
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="UserHistoryResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class UserHistoryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public UserHistoryResult() As ServiceReference1.CompositeType3
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserHistoryResult() As ServiceReference1.CompositeType3)
            MyBase.New
            Me.UserHistoryResult = UserHistoryResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EndGame", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class EndGameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public user1 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public user2 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public char1 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public char2 As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public victor As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal user1 As String, ByVal user2 As String, ByVal char1 As String, ByVal char2 As String, ByVal victor As Integer)
            MyBase.New
            Me.user1 = user1
            Me.user2 = user2
            Me.char1 = char1
            Me.char2 = char2
            Me.victor = victor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EndGameResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class EndGameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EndGameResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EndGameResult As Integer)
            MyBase.New
            Me.EndGameResult = EndGameResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ChampData", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ChampDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public c As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal c As Integer)
            MyBase.New
            Me.c = c
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ChampDataResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ChampDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public ChampDataResult As ServiceReference1.CompositeType4
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ChampDataResult As ServiceReference1.CompositeType4)
            MyBase.New
            Me.ChampDataResult = ChampDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ChampName", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ChampNameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public c As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal c As Integer)
            MyBase.New
            Me.c = c
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ChampNameResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ChampNameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public ChampNameResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ChampNameResult As String)
            MyBase.New
            Me.ChampNameResult = ChampNameResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="BotFight", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class BotFightRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Atacker As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public myrobot As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public myaction As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public hisrobot As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public hisaction As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Atacker As String, ByVal myrobot As String, ByVal myaction As Integer, ByVal hisrobot As String, ByVal hisaction As Integer)
            MyBase.New
            Me.Atacker = Atacker
            Me.myrobot = myrobot
            Me.myaction = myaction
            Me.hisrobot = hisrobot
            Me.hisaction = hisaction
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="BotFightResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class BotFightResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public BotFightResult As ServiceReference1.CompositeType5
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal BotFightResult As ServiceReference1.CompositeType5)
            MyBase.New
            Me.BotFightResult = BotFightResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ServiceReference1.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IService1)
        Implements ServiceReference1.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CheckLogin(ByVal request As ServiceReference1.CheckLoginRequest) As ServiceReference1.CheckLoginResponse Implements ServiceReference1.IService1.CheckLogin
            Return MyBase.Channel.CheckLogin(request)
        End Function
        
        Public Function Top10(ByVal request As ServiceReference1.Top10Request) As ServiceReference1.Top10Response Implements ServiceReference1.IService1.Top10
            Return MyBase.Channel.Top10(request)
        End Function
        
        Public Function Rank(ByVal request As ServiceReference1.RankRequest) As ServiceReference1.RankResponse Implements ServiceReference1.IService1.Rank
            Return MyBase.Channel.Rank(request)
        End Function
        
        Public Function Scor(ByVal request As ServiceReference1.ScorRequest) As ServiceReference1.ScorResponse Implements ServiceReference1.IService1.Scor
            Return MyBase.Channel.Scor(request)
        End Function
        
        Public Function UserNou(ByVal request As ServiceReference1.UserNouRequest) As ServiceReference1.UserNouResponse Implements ServiceReference1.IService1.UserNou
            Return MyBase.Channel.UserNou(request)
        End Function
        
        Public Function Clasament(ByVal request As ServiceReference1.ClasamentRequest) As ServiceReference1.ClasamentResponse Implements ServiceReference1.IService1.Clasament
            Return MyBase.Channel.Clasament(request)
        End Function
        
        Public Function Clasamentusr(ByVal request As ServiceReference1.ClasamentusrRequest) As ServiceReference1.ClasamentusrResponse Implements ServiceReference1.IService1.Clasamentusr
            Return MyBase.Channel.Clasamentusr(request)
        End Function
        
        Public Function UserHistory(ByVal request As ServiceReference1.UserHistoryRequest) As ServiceReference1.UserHistoryResponse Implements ServiceReference1.IService1.UserHistory
            Return MyBase.Channel.UserHistory(request)
        End Function
        
        Public Function EndGame(ByVal request As ServiceReference1.EndGameRequest) As ServiceReference1.EndGameResponse Implements ServiceReference1.IService1.EndGame
            Return MyBase.Channel.EndGame(request)
        End Function
        
        Public Function ChampData(ByVal request As ServiceReference1.ChampDataRequest) As ServiceReference1.ChampDataResponse Implements ServiceReference1.IService1.ChampData
            Return MyBase.Channel.ChampData(request)
        End Function
        
        Public Function ChampName(ByVal request As ServiceReference1.ChampNameRequest) As ServiceReference1.ChampNameResponse Implements ServiceReference1.IService1.ChampName
            Return MyBase.Channel.ChampName(request)
        End Function
        
        Public Function BotFight(ByVal request As ServiceReference1.BotFightRequest) As ServiceReference1.BotFightResponse Implements ServiceReference1.IService1.BotFight
            Return MyBase.Channel.BotFight(request)
        End Function
    End Class
End Namespace
